FROM golang:1.22-alpine

RUN apk add git

WORKDIR /go/src/github.com/fako1024/cmdchat
COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o cmdchat-server ./server

#########################

FROM alpine:3.19

WORKDIR /
COPY --from=0 /go/src/github.com/fako1024/cmdchat/cmdchat-server /

RUN addgroup -g 10000 -S app && \
    adduser -u 10000 -S app -G app

USER app

CMD ["/cmdchat-server"]
